### PR TITLE
Illuc I made a pull request are you proud of me

### PR DESCRIPTION
**Pull request by Heisenberg1982**
I fixed some visual stuff that was annoying me like the gyro display and some lang stuff.

### CODE REVIEW

**Comment by Rulft44** [comment]
I had already made a pull request with that stuff :sob:

**Comment by Heisenberg1982** [comment]
But I made these changes 😭

Op do 21 dec. 2023 om 14:23 schreef Rulft44 ***@***.***>

**Comment by Rulft44** [comment]
> I had already made a pull request with that stuff 😭

Wait I’m dum dum and never actually posted it nvm 😭

**Comment by illucc** [comment]
Im proud 🥹

**Comment by Heisenberg1982** [comment]
Yay! :3

**Comment by Sascha-T** [comment]
grafik
heisen what kind of creature are you

**Comment by Heisenberg1982** [comment]
Idk I got a mail so I responded here :clueless:

**Pull request merged**
